jobs:
- job: BuildLinux
  pool:
    vmImage: 'ubuntu-18.04'

  timeoutInMinutes: 360

  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: s3cfg
  - script: ci/azure/linux_script
    name: main
    displayName: 'Build and test'
